server {
    listen 80;
    server_tokens off;
    root /usr/share/nginx/html;
    location = /health { access_log off; return 200 "OK"; }
    location /database-editor/assets/ { try_files $uri =404; }
    location /database-editor/ {
        add_header Cache-Control "no-store" always;
        try_files $uri $uri/ /database-editor/index.html;
    }
    location / { return 404; }
}
